apps/Administrador/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Administrador.views import index_administrador, bin_view, pestana_view, ATM_view, Estado_view, Estado_iniciativa_view, Tipo_iniciativa_view, Desarrollador_view, Perfil_view, Usuario_view, CPM_view, bin_list, bin_edit, bin_delete, atm_list, atm_edit, atm_delete, pestana_list, pestana_edit, pestana_delete, estado_list, estado_edit, estado_delete, caso_list, caso_edit, caso_delete, tipo_list, tipo_edit, tipo_delete, estadoi_list, estadoi_edit, estadoi_delete, usuario_list, usuario_edit, usuario_delete, desarrollador_list, desarrollador_edit, desarrollador_delete, perfil_list, perfil_edit, perfil_delete, binlist, perfillist, pestanalist

urlpatterns = [
    url(r'^$', index_administrador, name = 'index_administrador'),
    url(r'^nuevo_bin$', bin_view, name = 'bin_crear'),
    url(r'^nueva_pestana$', pestana_view, name = 'pestana_crear'),
    url(r'^nuevo_atm$', ATM_view, name = 'ATM_crear'),
    url(r'^nuevo_estado$', Estado_view, name = 'Estado_crear'),
    url(r'^nuevo_estadoi$', Estado_iniciativa_view, name = 'Estadoi_crear'),
    url(r'^nuevo_tipoi$', Tipo_iniciativa_view, name = 'Tipoi_crear'),
    url(r'^nuevo_desarrollador$', Desarrollador_view, name = 'Desarrollador_crear'),
    url(r'^nuevo_perfil$', Perfil_view, name = 'Perfil_crear'),
    url(r'^nuevo_usuario$', Usuario_view, name = 'Usuario_crear'),
    url(r'^nuevo_cpm$', CPM_view, name = 'CPM_crear'),
    url(r'^listar_bin', binlist.as_view(), name = 'Bin_listar'),
    url(r'^editar/(?P<id_Bin>\d+)/$', bin_edit, name = 'Bin_editar'),
    url(r'^eliminar/(?P<id_Bin>\d+)/$', bin_delete, name = 'Bin_eliminar'),
    url(r'^listar_atm$', atm_list, name = 'Atm_listar'),
    url(r'^editar1/(?P<id_ATM>\d+)/$', atm_edit, name = 'Atm_editar'),
    url(r'^eliminar1/(?P<id_ATM>\d+)/$', atm_delete, name = 'Atm_eliminar'),
    url(r'^listar_pestana', pestanalist.as_view(), name = 'Pestana_listar'),
    url(r'^editar2/(?P<id_pestana>\d+)/$', pestana_edit, name = 'Pestana_editar'),
    url(r'^eliminar2/(?P<id_pestana>\d+)/$', pestana_delete, name = 'Pestana_eliminar'),
    url(r'^listar_estado$', estado_list, name = 'Estado_listar'),
    url(r'^editar3/(?P<id_Estado>\d+)/$', estado_edit, name = 'Estado_editar'),
    url(r'^eliminar3/(?P<id_Estado>\d+)/$', estado_delete, name = 'Estado_eliminar'),
    url(r'^listar_caso$', caso_list, name = 'Caso_listar'),
    url(r'^editar4/(?P<id_CasoPrueba>\d+)/$', caso_edit, name = 'Caso_editar'),
    url(r'^eliminar4/(?P<id_CasoPrueba>\d+)/$', caso_delete, name = 'Caso_eliminar'),
    url(r'^listar_tipo$', tipo_list, name = 'Tipo_listar'),
    url(r'^editar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_edit, name = 'Tipo_editar'),
    url(r'^eliminar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_delete, name = 'Tipo_eliminar'),
    url(r'^listar_estadoi$', estadoi_list, name = 'Estadoi_listar'),
    url(r'^editar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_edit, name = 'Estadoi_editar'),
    url(r'^eliminar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_delete, name = 'Estadoi_eliminar'),
    url(r'^listar_usuario$', usuario_list, name = 'Usuario_listar'),
    url(r'^editar7/(?P<id_Usuario>\d+)/$', usuario_edit, name = 'Usuario_editar'),
    url(r'^eliminar7/(?P<id_Usuario>\d+)/$', usuario_delete, name = 'Usuario_eliminar'),
    url(r'^listar_desarrollador$', desarrollador_list, name = 'Desarrollador_listar'),
    url(r'^editar8/(?P<id_Desarrollador>\d+)/$', desarrollador_edit, name = 'Desarrollador_editar'),
    url(r'^eliminar8/(?P<id_Desarrollador>\d+)/$', desarrollador_delete, name = 'Desarrollador_eliminar'),
    url(r'^listar_perfil', perfillist.as_view(), name = 'Perfil_listar'),
    url(r'^editar9/(?P<id_Perfil>\d+)/$', perfil_edit, name = 'Perfil_editar'),
    url(r'^eliminar9/(?P<id_Perfil>\d+)/$', perfil_delete, name = 'Perfil_eliminar'),

]

apps/Certificador/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Certificador.views import index_certificador

urlpatterns = [
    url(r'^$', index_certificador)
]

apps/Gestor/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Gestor.views import index_gestor, iniciativa_view, iniciativa_edit, iniciativa_list, iniciativalist,  asignacion_list, asignacion_edit, asignacion_delete, asignacionlist, AsignacionCreate

urlpatterns = [
    url(r'^$', index_gestor, name ='index_gestor'),
    url(r'^nueva_iniciativa$', iniciativa_view, name = 'iniciativa_crear'),
    url(r'^listar_iniciativa', iniciativalist.as_view(), name = 'Iniciativa_listar'),
    url(r'^editar10/(?P<id_Iniciativa>\d+)/$', iniciativa_edit, name = 'Iniciativa_editar'),
    url(r'^nuevo_asignacion$', AsignacionCreate.as_view(), name = 'Asignacion_crear'),
    url(r'^listar_asignacion', asignacionlist.as_view(), name = 'Asignacion_listar'),
    url(r'^editar15/(?P<id>\d+)/$', asignacion_edit, name = 'Asignacion_editar'),
    url(r'^eliminar15/(?P<id>\d+)/$', asignacion_delete, name = 'Asignacion_eliminar'),

]

apps/usuario/urls.py
from __future__ import absolute_import
from django.conf.urls import url


from apps.usuario.views import RegistroUsuario, ProfileList, ProfileCreate, ProfileUpdate, ProfileDelete, GestorList, GestorCreate, GestorUpdate, GestorDelete, CertificadoresList, CertificadoresCreate, CertificadoresUpdate, CertificadoresDelete


urlpatterns = [
    url(r'^registrar', RegistroUsuario.as_view(), name = "registrar"),
    url(r'^profile/listar_profile$', ProfileList.as_view(), name = 'Profile_listar'),
    url(r'^profile/nueva_profile$', ProfileCreate.as_view(), name = 'Profile_nueva'),
    url(r'^profile/editar_profile/(?P<pk>\d+)$', ProfileUpdate.as_view(), name = 'Profile_editar'),
    url(r'^profile/eliminar_profile/(?P<pk>\d+)$', ProfileDelete.as_view(), name = 'Profile_eliminar'),
    url(r'^gestor/listar_gestor$', GestorList.as_view(), name = 'Gestor_listar'),
    url(r'^gestor/nueva_gestor$', GestorCreate.as_view(), name = 'Gestor_nueva'),
    url(r'^gestor/editar_gestor/(?P<pk>\d+)$', GestorUpdate.as_view(), name = 'Gestor_editar'),
    url(r'^gestor/eliminar_gestor/(?P<pk>\d+)$', GestorDelete.as_view(), name = 'Gestor_eliminar'),
    url(r'^gestor/listar_certificador$', CertificadoresList.as_view(), name = 'Certificador_listar'),
    url(r'^gestor/nueva_certificador$', CertificadoresCreate.as_view(), name = 'Certificador_nueva'),
    url(r'^gestor/editar_certificador/(?P<pk>\d+)$', CertificadoresUpdate.as_view(), name = 'Certificador_editar'),
    url(r'^gestor/eliminar_certificador/(?P<pk>\d+)$', CertificadoresDelete.as_view(), name = 'Certificador_eliminar'),


]

tesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [

url(r'^admin/', admin.site.urls),
url(r'^administrador/', include ('apps.Administrador.urls', namespace = "administrador")),
url(r'^gestor/', include ('apps.Gestor.urls', namespace = "gestor")),
url(r'^certificador/', include ('apps.Certificador.urls', namespace = "certificador")),
url(r'^usuario/', include ('apps.usuario.urls', namespace = "usuario")),
url(r'^$', login, {'template_name':'usuario/index.html'}, name = 'login')
]

apps/Certificador/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, null = False, blank= True, on_delete = models.CASCADE)
    nombre = models.CharField(max_length=50, null = False, blank= True)
    perfil = models.CharField(max_length=50, null = False, blank= True)
    correo = models.CharField(max_length=250, null = False, blank= True)

    def __str__(self):
        return'{}'.format(self.nombre)

class Gestores(models.Model):
    user = models.ForeignKey(User, null = True, blank= True, on_delete = models.CASCADE)
    nombre = models.CharField(max_length=50, null = True, blank= True)
    perfil = models.CharField(max_length=50, null = True, blank= True)
    correo = models.CharField(max_length=250, null = True, blank= True)

class Certificadores(models.Model):
    user = models.ForeignKey(User, null = True, blank= True, on_delete = models.CASCADE)
    nombre = models.CharField(max_length=50, null = True, blank= True)
    perfil = models.CharField(max_length=50, null = True, blank= True)
    correo = models.CharField(max_length=250, null = True, blank= True)

    def __str__(self):
        return'{}'.format(self.nombre)

apps/Gestor/forms.py
from __future__ import absolute_import
from django import forms
from apps.Gestor.models import Iniciativa, Asignacion
from apps.usuario.models import Profile



class IniciativaForm(forms.ModelForm):
    class Meta:
        model = Iniciativa

        fields =[
            'id_Iniciativa',
            'nombre',
            'cod_iniciativa',
            'descripcion',
            'tipo_iniciativa',
            'fecha_inicio',
            'fecha_cierre',
            'tipo_prueba',
            'tipo_desarrollo',
            'observaciones',
            'desarrollador',
            'estado_iniciativa',
        ]
        labels = {

            'id_Iniciativa': 'id_Iniciativa',
            'nombre': 'Nombre Iniciativa',
            'cod_iniciativa': 'Codigo de Iniciativa',
            'descripcion': 'Descripcion de Iniciativa',
            'tipo_iniciativa': 'Tipo de Iniciativa',
            'fecha_inicio': 'Fecha de inicio',
            'fecha_cierre': 'Fecha de Cierre',
            'tipo_prueba': 'Tipo de Flujo',
            'tipo_desarrollo': 'Tipo de Desarrollo',
            'observaciones': 'Observaciones',
            'desarrollador': 'JP Desarrollo',
            'estado_iniciativa': 'Estado de Iniciativa',
        }
        widgets = {
            'id_Iniciativa': forms.TextInput(attrs={'class':'form-control'}),
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'cod_iniciativa': forms.TextInput(attrs={'class':'form-control'}),
            'descripcion': forms.Textarea(attrs={'class':'form-control'}),
            'tipo_iniciativa': forms.Select(attrs={'class':'form-control'}),
            'fecha_inicio': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'fecha_cierre': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'tipo_prueba': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_desarrollo': forms.TextInput(attrs={'class':'form-control'}),
            'observaciones': forms.Textarea(attrs={'class':'form-control'}),
            'desarrollador': forms.Select(attrs={'class':'form-control'}),
            'estado_iniciativa': forms.HiddenInput(attrs={'class':'form-control', 'value' : 'Nuevo'}),

        }

class AsignacionForm(forms.ModelForm):

    class Meta:
        model = Asignacion

        fields =[

            'certificador',

        ]
        labels = {


            'certificador': 'Certificadores',

        }

    

apps/usuario/forms.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from apps.usuario.models import Profile, Gestores, Certificadores
class RegistroForm(UserCreationForm):
    class Meta:

        model = User
        fields =[
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Nombre de Usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo',
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile

        fields =[

            'nombre',
            'perfil',
            'correo',
        ]
        labels = {
            'nombre': 'Nombre Usuario',
            'perfil': 'Perfil Usuario',
            'correo': 'Correo Usuario',
        }
        widgets = {
            'nombre': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto2'}),
            'perfil': forms.HiddenInput(attrs={'class':'form-control', 'name':'Precio', 'id':'Precio'}),
            'correo': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto4'}),
}

class GestorForm(forms.ModelForm):
    class Meta:
        model = Gestores

        fields =[

            'nombre',
            'perfil',
            'correo',
        ]
        labels = {
            'nombre': 'Nombre Usuario',
            'perfil': 'Perfil Usuario',
            'correo': 'Correo Usuario',
        }
        widgets = {
            'nombre': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto2'}),
            'perfil': forms.HiddenInput(attrs={'class':'form-control', 'name':'Precio', 'id':'Precio'}),
            'correo': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto4'}),
        }

class CertificadoresForm(forms.ModelForm):
    class Meta:
        model = Certificadores

        fields =[

            'nombre',
            'perfil',
            'correo',
        ]
        labels = {
            'nombre': 'Nombre Usuario',
            'perfil': 'Perfil Usuario',
            'correo': 'Correo Usuario',
        }
        widgets = {
            'nombre': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto2'}),
            'perfil': forms.HiddenInput(attrs={'class':'form-control', 'name':'Precio', 'id':'Precio'}),
            'correo': forms.HiddenInput(attrs={'class':'form-control', 'id':'texto4'}),

        }

apps/Certificador/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.shortcuts import render
from django.http import HttpResponse

def index_certificador(request):
    return render(request, 'certificacion/index.html')

# Create your views here.

apps/Gestor/views.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from apps.Gestor.forms import IniciativaForm, AsignacionForm
from apps.Gestor.models import Iniciativa, Asignacion
from apps.usuario.models import Profile


# Create your views here.
def index_gestor(request):
    return render(request, 'gestion/index.html')

def iniciativa_view(request):
    if request.method == 'POST':
        form = IniciativaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('gestor:Iniciativa_listar')
    else:
        form = IniciativaForm()
    return render(request, 'gestion/iniciativa_ingresar.html', {'form': form})


def iniciativa_list(request):
    iniciativa = Iniciativa.objects.all().order_by('id_Iniciativa')
    contexto = {'iniciativas':iniciativa}
    return render(request, 'gestion/iniciativa_lista.html', contexto)

def iniciativa_edit(request, id_Iniciativa):
    iniciativa = Iniciativa.objects.get(id_Iniciativa =id_Iniciativa)
    if request.method == 'GET':
        form = IniciativaForm(instance = iniciativa)
    else:
        form = IniciativaForm(request.POST, instance = iniciativa)
        if form.is_valid():
            form.save()
        return redirect('gestor:Iniciativa_listar')
    return render(request, 'gestion/iniciativa_ingresar.html', {'form': form})

class iniciativalist(ListView):
    model = Iniciativa
    template_name = 'gestion/iniciativa_lista.html'
    paginate_by = 3

class AsignacionCreate(CreateView):
    model= Asignacion
    second_model= Profile
    template_name = 'gestion/asignacion_ingresar.html'
    form_class = AsignacionForm
    success_url = reverse_lazy('gestor:Asignacion_listar')

def asignacion_view(request):

    if request.method == 'POST':
        form = AsignacionForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('gestor:Asignacion_listar')
    else:
        form = AsignacionForm()
    return render(request, 'gestion/asignacion_ingresar.html', {'form': form})

def asignacion_list(request):
    asignacion = Asignacion.objects.all().order_by('id')
    contexto = {'asignacions':asignacion}
    return render(request, 'gestion/asignacion_lista.html', contexto)

def asignacion_edit(request, id):
    asignacion = Asignacion.objects.get(id =id)
    if request.method == 'GET':
        form = AsignacionForm(instance = asignacion)
    else:
        form = AsignacionForm(request.POST, instance = asignacion)
        if form.is_valid():
            form.save()
        return redirect('gestor:Asignacion_listar')
    return render(request, 'gestion/asignacion_ingresar.html', {'form': form})

def asignacion_delete(request, id):
    asignacion = Asignacion.objects.get(id =id)
    if request.method == 'POST':
        asignacion.delete()
        return redirect('gestor:Asignacion_listar')
    return render(request, 'gestion/asignacion_delete.html', {'asignacion': asignacion})

class asignacionlist(ListView):
    model = Asignacion
    template_name = 'gestion/asignacion_lista.html'
    paginate_by = 2

templates/usuario/bin_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar BIN
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ bin.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Bin_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/usuario/certificador_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Certificador
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ user.first_name }} ?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'usuario:Certificador_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/usuario/certificador_form.html
{% extends 'administracion/index.html' %}
{% block title %}
Registrar Certificador
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}

<form id="form2"  method="post" autocomplete="off">
  {% csrf_token %}
  {{ form.as_p }}
  <script src="http://code.jquery.com/jquery-1.0.4.js"></script>
  <script>
        $(document).ready(function () {
            $("#texto1").keyup(function () {
                var value = $(this).val();
                $("#texto2").val(value);
            });
        });
  </script>
  <script>
        $(document).ready(function () {
            $("#texto3").keyup(function () {
                var value = $(this).val();
                $("#texto4").val(value);
            });
        });
  </script>


  <script type="text/javascript">
      function FijarPrecio(id){
         var PrecioSel = document.getElementById(id);
         var PrecioActual = document.getElementById('Precio');
         PrecioActual.value = PrecioSel.value;
      }
  </script>


  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group" >
        <label>Nombre y Apellido</label>
        <input class="form-control"  type="text" name="first_name" id="texto1" required value="{{certificador.nombre}}">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <label for="options1">Perfil</label>
            <select name="last_name"  class="form-control" id="Seleccionar" onchange="FijarPrecio(this.id);" required value="{{certificador.perfil}}">
            	<option value="" ></option>
            	<option value="Certificador">Certificador</option>
            </select>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <label>Nombre de Usuario</label>
        <input class="form-control" type="text" name="username" required>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <label>Correo</label>
        <input class="form-control" type="text" name="email" id="texto3" required value="{{certificador.correo}}">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <label>Contraseña</label>
        <input class="form-control" type="password" name="password1" required>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <label>Confirmar Contraseña</label>
        <input class="form-control" type="password" name="password2" required>
      </div>
    </div>
  </div>

  <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
      </div>
  </div>
</form>
{% endblock %}
{% block footer %}
{% endblock %}

templates/usuario/certificador_list.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Certificadores
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre Usuario</th>
        <th>Perfil Usuario</th>
        <th>Correo Usuario</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for certificador in object_list %}
      <tr>
        <td>{{certificador.nombre}}</td>
        <td>{{certificador.perfil}}</td>
        <td>{{certificador.correo}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'usuario:Certificador_editar' certificador.id %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'usuario:Certificador_eliminar' certificador.user_id %}">Eliminar</a>

        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Certificadores</h1>

      {% endif %}

    </tbody>
  </table>
    <ul class="pager">
      <li>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
        {% endif %}
      </li>
      <li>
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Proximo</a>
        {% endif %}
      </li>
    </ul>
{% endblock %}
{% block footer %}
{% endblock %}

templates/usuario/gestor_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Gestor
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ user.first_name }} ?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'usuario:Gestor_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/usuario/gestor_list.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Gestores
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre Usuario</th>
        <th>Perfil Usuario</th>
        <th>Correo Usuario</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for gestor in object_list %}
      <tr>
        <td>{{gestor.nombre}}</td>
        <td>{{gestor.perfil}}</td>
        <td>{{gestor.correo}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'usuario:Gestor_editar' gestor.id %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'usuario:Gestor_eliminar' gestor.user_id %}">Eliminar</a>

        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Usuarios</h1>

      {% endif %}

    </tbody>
  </table>
    <ul class="pager">
      <li>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
        {% endif %}
      </li>
      <li>
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Proximo</a>
        {% endif %}
      </li>
    </ul>
{% endblock %}
{% block footer %}
{% endblock %}

templates/usuario/profile_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Usuario
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ profile.nombre }} ?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'usuario:Profile_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/usuario/profile_list.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Usuarios
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre Usuario</th>
        <th>Perfil Usuario</th>
        <th>Correo Usuario</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for profile in object_list %}
      <tr>
        <td>{{profile.nombre}}</td>
        <td>{{profile.perfil}}</td>
        <td>{{profile.correo}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'usuario:Profile_editar' profile.id %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'usuario:Profile_eliminar' profile.user_id %}">Eliminar</a>

        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Usuarios</h1>

      {% endif %}

    </tbody>
  </table>
    <ul class="pager">
      <li>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
        {% endif %}
      </li>
      <li>
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Proximo</a>
        {% endif %}
      </li>
    </ul>
{% endblock %}
{% block footer %}

{% endblock %}