apps/Gestor/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Gestor.views import index_gestor, iniciativa_view, iniciativa_edit, iniciativa_list, iniciativalist,  asignacion_list, asignacion_edit, asignacion_delete, asignacionlist, AsignacionCreate

urlpatterns = [
    url(r'^$', index_gestor, name ='index_gestor'),
    url(r'^nueva_iniciativa$', iniciativa_view, name = 'iniciativa_crear'),
    url(r'^listar_iniciativa', iniciativalist.as_view(), name = 'Iniciativa_listar'),
    url(r'^editar10/(?P<id_Iniciativa>\d+)/$', iniciativa_edit, name = 'Iniciativa_editar'),
    url(r'^nuevo_asignacion$', AsignacionCreate.as_view(), name = 'Asignacion_crear'),
    url(r'^listar_asignacion', asignacionlist.as_view(), name = 'Asignacion_listar'),
    url(r'^editar15/(?P<id>\d+)/$', asignacion_edit, name = 'Asignacion_editar'),
    url(r'^eliminar15/(?P<id>\d+)/$', asignacion_delete, name = 'Asignacion_eliminar'),

]

tesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [

url(r'^admin/', admin.site.urls),
url(r'^administrador/', include ('apps.Administrador.urls', namespace = "administrador")),
url(r'^gestor/', include ('apps.Gestor.urls', namespace = "gestor")),
url(r'^certificador/', include ('apps.Certificador.urls', namespace = "certificador")),
url(r'^usuario/', include ('apps.usuario.urls', namespace = "usuario")),
url(r'^$', login, {'template_name':'usuario/index.html'}, name = 'login')
]

templates/gestion/asignacion_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Asignacion
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro {{asignacion.certificador}}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'gestor:Asignacion_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/gestion/asignacion_ingresar.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="form-group">
      <label for="options1">Certificadores</label>
          <select name="certificador"  class="form-control">
              {% for profile in object_list %}
            <option value="{{profile.nombre}}">{{profile.nombre}}</option>
                {% endfor %}
          </select>
    </div>
  </div>
</div>
<button type="submit" class="btn btn-primary">Asignar</button>
</form>
{% endblock %}



{% block footer %}

<footer class="mt-5">
  <div style="width: 100%; height: 90px; background: #ffffff; bottom: 0; position: static;margin-top: 20px; ">
    <img src="../static/imagen/Redbanc vector logo.png" alt="Redbanc" align = "right" width="250px">
      <img src="../static/imagen/logos.png" alt="Redbanc" align = "left" style="margin-top : 15px;">

  </div>
</footer>

{% endblock %}

templates/gestion/asignacion_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Asignaciones
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Iniciativas</th>
        <th>Certificadores</th>
        <th>Pestanas</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for asignacion in object_list %}
      <tr>
        <td>{{asignacion.iniciativa}}</td>
        <td>{{asignacion.certificador}}</td>
        <td>{% for pestana in asignacion.pestanas.all %}
                {{ pestana.nombre }}
            {% endfor %}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'gestor:Asignacion_editar' asignacion.id %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'gestor:Asignacion_eliminar' asignacion.id %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Asignaciones</h1>
      {% endif %}
        <table class="table table-striped table-hover " name = "tablap">
        </table>
  <ul class="pager">
    <li>
      {% if page_obj.has_previous %}
      <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
      {% endif %}
    </li>
    <li>
      {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}">Proximo</a>
      {% endif %}
    </li>
  </ul>

{% endblock %}

templates/gestion/certificador_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Iniciativas
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Certificador</th>
        <th>Seleccionar</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for usuario in object_list %}
      <tr>
        <td>{{usuario.first_name}}</td>
        <td>
          <input type="checkbox" class="custom-control-input">
        <td>
          <a  class="btn btn-primary" >Asignar</a>
        </td>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Iniciativas</h1>

      {% endif %}
    </tbody>
  </table>
{% endblock %}

templates/gestion/index.html
{% extends 'base/base.html' %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Gestor</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Iniciativa
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Crear Iniciativa</a></li>
          <li><a href="#">Listado de Iniciativas</a></li>
          <li><a href="#">Enviar Correo de Asignación</a></li>
          <li><a href="#">Enviar Correo de Notificación</a></li>
        </ul>
      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="#"><span class="active"></span> Cerrar Sesión</a></li>
  </ul>
  </div>
</nav>
{% endblock %}

{% block title %}
Gestor
{% endblock %}

{% block header %}
<h3>BIENVENIDO GESTOR</h3>
{% endblock %}

{% block content %}
{% endblock %}

templates/gestion/iniciativa_ingresar.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-primary">OK</button>
</form>
{% endblock %}
{% block footer %}

<footer class="mt-5">
  <div style="width: 100%; height: 90px; background: #ffffff; bottom: 0; position: static;margin-top: 20px; ">
    <img src="../static/imagen/Redbanc vector logo.png" alt="Redbanc" align = "right" width="250px">
      <img src="../static/imagen/logos.png" alt="Redbanc" align = "left" style="margin-top : 15px;">

  </div>
</footer>

{% endblock %}

templates/gestion/iniciativa_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Iniciativas
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Codigo</th>
        <th>Descripcion</th>
        <th>Tipo Iniciativa</th>
        <th>Estado</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for iniciativa in object_list %}
      <tr>
        <td>{{iniciativa.nombre}}</td>
        <td>{{iniciativa.cod_iniciativa}}</td>
        <td>{{iniciativa.descripcion}}</td>
        <td>{{iniciativa.tipo_iniciativa}}</td>
        <td>{{iniciativa.estado_iniciativa}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'gestor:Iniciativa_editar' iniciativa.id_Iniciativa %}">Editar</a>

        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Iniciativas</h1>

      {% endif %}
    </tbody>
  </table>
    <ul class="pager">
      <li>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
        {% endif %}
      </li>
      <li>
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Proximo</a>
        {% endif %}
      </li>
    </ul>
{% endblock %}

templates/gestion/iniciativas_ingresar.html
{% extends 'administracion/index.html' %}
{% block title %}
Asignar Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="form-group">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Certificador</th>
            <th>Seleccionar</th>
          </tr>
        </thead>
        <tbody>
          {% if object_list %}
          {% for usuario in object_list %}
          <tr>
            <td>{{usuario.first_name}}</td>
            <td>
              <input name="certificador" type="checkbox" class="custom-control-input">
            <td>
              <a  class="btn btn-primary" >Asignar</a>
            </td>
            </td>
          </tr>
          {% endfor %}

          {% endif %}
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
      <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
      </div>
  </div>

</div>
</form>
{% endblock %}