apps/Administrador/urls.py
from __future__ import absolute_import
from django.conf.urls import url, include
from apps.Administrador.views import index_administrador, bin_view, pestana_view, ATM_view, Estado_view, Estado_iniciativa_view, Tipo_iniciativa_view, Desarrollador_view, Perfil_view, Usuario_view, CPM_view, bin_list, bin_edit, bin_delete, atm_list, atm_edit, atm_delete, pestana_list, pestana_edit, pestana_delete, estado_list, estado_edit, estado_delete, caso_list, caso_edit, caso_delete, tipo_list, tipo_edit, tipo_delete, estadoi_list, estadoi_edit, estadoi_delete, usuario_list, usuario_edit, usuario_delete, desarrollador_list, desarrollador_edit, desarrollador_delete, perfil_list, perfil_edit, perfil_delete, binlist, perfillist, pestanalist

urlpatterns = [
    url(r'^$', index_administrador, name = 'index_administrador'),
    url(r'^nuevo_bin$', bin_view, name = 'bin_crear'),
    url(r'^nueva_pestana$', pestana_view, name = 'pestana_crear'),
    url(r'^nuevo_atm$', ATM_view, name = 'ATM_crear'),
    url(r'^nuevo_estado$', Estado_view, name = 'Estado_crear'),
    url(r'^nuevo_estadoi$', Estado_iniciativa_view, name = 'Estadoi_crear'),
    url(r'^nuevo_tipoi$', Tipo_iniciativa_view, name = 'Tipoi_crear'),
    url(r'^nuevo_desarrollador$', Desarrollador_view, name = 'Desarrollador_crear'),
    url(r'^nuevo_perfil$', Perfil_view, name = 'Perfil_crear'),
    url(r'^nuevo_usuario$', Usuario_view, name = 'Usuario_crear'),
    url(r'^nuevo_cpm$', CPM_view, name = 'CPM_crear'),
    url(r'^listar_bin', binlist.as_view(), name = 'Bin_listar'),
    url(r'^editar/(?P<id_Bin>\d+)/$', bin_edit, name = 'Bin_editar'),
    url(r'^eliminar/(?P<id_Bin>\d+)/$', bin_delete, name = 'Bin_eliminar'),
    url(r'^listar_atm$', atm_list, name = 'Atm_listar'),
    url(r'^editar1/(?P<id_ATM>\d+)/$', atm_edit, name = 'Atm_editar'),
    url(r'^eliminar1/(?P<id_ATM>\d+)/$', atm_delete, name = 'Atm_eliminar'),
    url(r'^listar_pestana', pestanalist.as_view(), name = 'Pestana_listar'),
    url(r'^editar2/(?P<id_pestana>\d+)/$', pestana_edit, name = 'Pestana_editar'),
    url(r'^eliminar2/(?P<id_pestana>\d+)/$', pestana_delete, name = 'Pestana_eliminar'),
    url(r'^listar_estado$', estado_list, name = 'Estado_listar'),
    url(r'^editar3/(?P<id_Estado>\d+)/$', estado_edit, name = 'Estado_editar'),
    url(r'^eliminar3/(?P<id_Estado>\d+)/$', estado_delete, name = 'Estado_eliminar'),
    url(r'^listar_caso$', caso_list, name = 'Caso_listar'),
    url(r'^editar4/(?P<id_CasoPrueba>\d+)/$', caso_edit, name = 'Caso_editar'),
    url(r'^eliminar4/(?P<id_CasoPrueba>\d+)/$', caso_delete, name = 'Caso_eliminar'),
    url(r'^listar_tipo$', tipo_list, name = 'Tipo_listar'),
    url(r'^editar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_edit, name = 'Tipo_editar'),
    url(r'^eliminar5/(?P<id_Tipo_iniciativa>\d+)/$', tipo_delete, name = 'Tipo_eliminar'),
    url(r'^listar_estadoi$', estadoi_list, name = 'Estadoi_listar'),
    url(r'^editar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_edit, name = 'Estadoi_editar'),
    url(r'^eliminar6/(?P<id_Estado_iniciativa>\d+)/$', estadoi_delete, name = 'Estadoi_eliminar'),
    url(r'^listar_usuario$', usuario_list, name = 'Usuario_listar'),
    url(r'^editar7/(?P<id_Usuario>\d+)/$', usuario_edit, name = 'Usuario_editar'),
    url(r'^eliminar7/(?P<id_Usuario>\d+)/$', usuario_delete, name = 'Usuario_eliminar'),
    url(r'^listar_desarrollador$', desarrollador_list, name = 'Desarrollador_listar'),
    url(r'^editar8/(?P<id_Desarrollador>\d+)/$', desarrollador_edit, name = 'Desarrollador_editar'),
    url(r'^eliminar8/(?P<id_Desarrollador>\d+)/$', desarrollador_delete, name = 'Desarrollador_eliminar'),
    url(r'^listar_perfil', perfillist.as_view(), name = 'Perfil_listar'),
    url(r'^editar9/(?P<id_Perfil>\d+)/$', perfil_edit, name = 'Perfil_editar'),
    url(r'^eliminar9/(?P<id_Perfil>\d+)/$', perfil_delete, name = 'Perfil_eliminar'),

]

tesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [

url(r'^admin/', admin.site.urls),
url(r'^administrador/', include ('apps.Administrador.urls', namespace = "administrador")),
url(r'^gestor/', include ('apps.Gestor.urls', namespace = "gestor")),
url(r'^certificador/', include ('apps.Certificador.urls', namespace = "certificador")),
url(r'^usuario/', include ('apps.usuario.urls', namespace = "usuario")),
url(r'^$', login, {'template_name':'usuario/index.html'}, name = 'login')
]

templates/administracion/bin_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de BINES
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>BIN</th>
        <th>Banco BIN</th>
        <th>Tipo de Producto</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
      {% for bin in object_list %}
      <tr>
        <td>{{bin.nombre}}</td>
        <td>{{bin.banco}}</td>
        <td>{{bin.producto}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'administrador:Bin_editar' bin.id_Bin %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'administrador:Bin_eliminar' bin.id_Bin %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de BINES</h1>

      {% endif %}

    </tbody>
  </table>
    <ul class="pager">
      <li>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
        {% endif %}
      </li>
      <li>
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Proximo</a>
        {% endif %}
      </li>
    </ul>
{% endblock %}

templates/administracion/caso_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Casos de Pruebas Maestros
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Pestana</th>
        <th>Tipo de Prueba</th>
        <th>ATM</th>
        <th>BIN</th>
        <th>Prueba</th>
        <th>Descripcion de Prueba</th>
        <th>Resultado Esperado</th>
        <th>Fecha</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if casos %}
      {% for caso in casos %}
      <tr>
        <td>{{caso.pestana}}</td>
        <td>{{caso.tipo_prueba}}</td>
        <td>{{caso.ATM}}</td>
        <td>{{caso.bin}}</td>
        <td>{{caso.trx}}</td>
        <td>{{caso.prueba}}</td>
        <td>{{caso.resultado_esperado}}</td>
        <td>{{caso.fecha}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'administrador:Caso_editar' caso.id_CasoPrueba %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'administrador:Caso_eliminar' caso.id_CasoPrueba %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Casos de Pruebas</h1>

      {% endif %}
    </tbody>
  </table>
{% endblock %}

templates/administracion/caso_prueba_maestro.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar CPM
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}
{% block footer %}

<footer class="mt-5">
  <div style="width: 100%; height: 90px; background: #ffffff; bottom: 0; position: static;margin-top: 20px; ">
    <img src="../static/imagen/Redbanc vector logo.png" alt="Redbanc" align = "right" width="250px">
      <img src="../static/imagen/logos.png" alt="Redbanc" align = "left" style="margin-top : 15px;">

  </div>
</footer>

{% endblock %}

templates/administracion/desarrollador_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Desarrollador
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ desarrollador.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Desarrollador_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/administracion/estado_iniciativa.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar Estado Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/administracion/estado_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de ATM
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if estados %}
      {% for estado in estados %}
      <tr>
        <td>{{estado.nombre}}</td>
        <td>{{estado.descripcion}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'administrador:Estado_editar' estado.id_Estado %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'administrador:Estado_eliminar' estado.id_Estado %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Estados</h1>

      {% endif %}
    </tbody>
  </table>
{% endblock %}

templates/administracion/estadoi_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Estado de Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ estadoi.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Estadoi_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/administracion/estadoi_lista.html
{% extends 'administracion/index.html' %}
{% block title %}
Listado de Estados
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if estadois %}
      {% for estadoi in estadois %}
      <tr>
        <td>{{estadoi.nombre}}</td>
        <td>{{estadoi.descripcion}}</td>
        <td>
          <a  class="btn btn-primary" href="{% url 'administrador:Estadoi_editar' estadoi.id_Estado_iniciativa %}">Editar</a>
          <a  class="btn btn-danger" href="{% url 'administrador:Estadoi_eliminar' estadoi.id_Estado_iniciativa %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}

        <h1>No hay registros de Estados de Iniciativas</h1>

      {% endif %}
    </tbody>
  </table>
{% endblock %}

templates/administracion/index.html
{% extends 'base/base.html' %}

{% block title %}
{{user.last_name}}
{% endblock %}

{% block navbar %}
{% if user.last_name == 'Gestor' %}
<nav class="navbar navbar-default" style="background: #D92B36;">
  <div class="container-fluid" >
    <div class="navbar-header" >
      <a class="navbar-brand" href="http://127.0.0.1:8000/administrador/" >Gestor</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Iniciativa
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/gestor/nueva_iniciativa">Ingresar Nueva Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/gestor/listar_iniciativa">Listado de Iniciativas</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_tipoi">Ingresar Nuevo tipo de Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_tipo">Listado de Tipos de Iniciativas</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_estadoi">Ingresar Nuevo Estado de Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_estadoi">Listado de Estado de Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nueva_pestana">Ingresar Nueva Pestaña</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_pestana">Listado de Pestañas</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/profile/listar_profiles">Asignar Certificadores</a></li>
          <li><a href="http://127.0.0.1:8000/gestor/listar_asignacion">Listado de Asignaciones</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Ingresar
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_desarrollador">Ingresar Nuevo Desarrollador</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_desarrollador">Listado de Desarrolladores</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/gestor/nueva_certificador">Ingresar Nuevo Certificador</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/gestor/listar_certificador">Listado de Certificadores</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="http://127.0.0.1:8000"><span class="active"></span> Cerrar Sesión</a></li>
  </ul>
  </div>
</nav>
{% endif %}

{% if user.last_name == 'Administrador' %}
<nav class="navbar navbar-default" style="background: #D92B36;">
  <div class="container-fluid" >
    <div class="navbar-header" >
      <a class="navbar-brand" href="http://127.0.0.1:8000/administrador/" >Administrador</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Caso Prueba Maestro
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_cpm">Ingresar Caso de Prueba Maestro</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_caso">Listado de Casos de Prueba Maestros</a></li>
          <li><a href= "http://127.0.0.1:8000/administrador/nuevo_bin">Ingresar BIN</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_bin">Listado de BINES</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_atm">Ingresar ATM</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_atm">Listado de ATM</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_estado">Ingresar Nuevos Estado de CP</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_estado">Listado de Estados de CP</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nueva_pestana">Ingresar Nueva Pestaña</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_pestana">Listado de Pestañas</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Iniciativa
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_tipoi">Ingresar Nuevo tipo de Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_tipo">Listado de Tipos de Iniciativas</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_estadoi">Ingresar Nuevo Estado de Iniciativa</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_estadoi">Listado de Estado de Iniciativa</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nuevos Usuarios
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/usuario/gestor/nueva_gestor">Ingresar Nuevo Gestor</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/gestor/listar_gestor">Listado de Gestores</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/gestor/nueva_certificador">Ingresar Nuevo Certificador</a></li>
          <li><a href="http://127.0.0.1:8000/usuario/gestor/listar_certificador">Listado de Certificadores</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/nuevo_desarrollador">Ingresar Nuevo Desarrollador</a></li>
          <li><a href="http://127.0.0.1:8000/administrador/listar_desarrollador">Listado de Desarrolladores</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="http://127.0.0.1:8000"><span class="active"></span> Cerrar Sesión</a></li>
  </ul>
  </div>
</nav>
{% endif %}

{% if user.last_name == '' %}
<nav class="navbar navbar-default" style="background: #D92B36;">
  <div class="container-fluid" >
    <div class="navbar-header" >
      <a class="navbar-brand" href="http://127.0.0.1:8000/administrador/" >Administrador</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nuevo Usuario
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="http://127.0.0.1:8000/usuario/profile/nueva_profile">Ingresar Nuevo Usuario</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="http://127.0.0.1:8000"><span class="active"></span> Cerrar Sesión</a></li>
  </ul>
  </div>
</nav>
{% endif %}

{% if user.last_name == 'Certificador' %}
<nav class="navbar navbar-default" style="background: #D92B36;">
  <div class="container-fluid" >
    <div class="navbar-header" >
      <a class="navbar-brand" href="http://127.0.0.1:8000/administrador/" >Certificador</a>
    </div>
    <ul class="nav navbar-nav navbar-right">

    <li><a href="http://127.0.0.1:8000"><span class="active"></span> Cerrar Sesión</a></li>
  </ul>
  </div>
</nav>
{% endif %}
{% endblock %}

{% block header %}
<h3>BIENVENIDO {{user.last_name}} {{user.first_name}} </h3>
{% endblock %}
{% block content %}
{% if user.last_name == 'Certificador' %}
<img src="../static/imagen/warning.gif" height="400px" style="margin-left: 20%;">
{% endif %}
{% endblock %}

templates/administracion/perfil_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Perfil
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ perfil.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Perfil_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/administracion/perfil_ingresar.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar Perfil
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/administracion/pestana_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Pestana
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ pestana.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Pestana_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/administracion/pestana_ingresar.html
{% extends 'administracion/index.html' %}
{% block title %}
Ingresar Pestaña
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/administracion/tipo_delete.html
{% extends 'administracion/index.html' %}
{% block title %}
Eliminar Tipo de Iniciativa
{% endblock %}
{% block header %}
{% endblock %}
{%  block content %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el registro de {{ tipo.nombre }}?</h3>
  <button class="btn btn-danger" type="submit">Eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:Tipo_listar' %}">Cancelar</a>
</form>
{% endblock %}